# Generated by Django 4.2.2 on 2023-07-07 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(choices=[('ace', 'ace'), ('alpaca', 'alpaca'), ('ascendex', 'ascendex'), ('bequant', 'bequant'), ('bigone', 'bigone'), ('binance', 'binance'), ('binancecoinm', 'binancecoinm'), ('binanceus', 'binanceus'), ('binanceusdm', 'binanceusdm'), ('bit2c', 'bit2c'), ('bitbank', 'bitbank'), ('bitbay', 'bitbay'), ('bitbns', 'bitbns'), ('bitcoincom', 'bitcoincom'), ('bitfinex', 'bitfinex'), ('bitfinex2', 'bitfinex2'), ('bitflyer', 'bitflyer'), ('bitforex', 'bitforex'), ('bitget', 'bitget'), ('bithumb', 'bithumb'), ('bitmart', 'bitmart'), ('bitmex', 'bitmex'), ('bitopro', 'bitopro'), ('bitpanda', 'bitpanda'), ('bitrue', 'bitrue'), ('bitso', 'bitso'), ('bitstamp', 'bitstamp'), ('bitstamp1', 'bitstamp1'), ('bittrex', 'bittrex'), ('bitvavo', 'bitvavo'), ('bkex', 'bkex'), ('bl3p', 'bl3p'), ('blockchaincom', 'blockchaincom'), ('btcalpha', 'btcalpha'), ('btcbox', 'btcbox'), ('btcmarkets', 'btcmarkets'), ('btctradeua', 'btctradeua'), ('btcturk', 'btcturk'), ('bybit', 'bybit'), ('cex', 'cex'), ('coinbase', 'coinbase'), ('coinbaseprime', 'coinbaseprime'), ('coinbasepro', 'coinbasepro'), ('coincheck', 'coincheck'), ('coinex', 'coinex'), ('coinfalcon', 'coinfalcon'), ('coinmate', 'coinmate'), ('coinone', 'coinone'), ('coinsph', 'coinsph'), ('coinspot', 'coinspot'), ('cryptocom', 'cryptocom'), ('currencycom', 'currencycom'), ('delta', 'delta'), ('deribit', 'deribit'), ('digifinex', 'digifinex'), ('exmo', 'exmo'), ('fmfwio', 'fmfwio'), ('gate', 'gate'), ('gateio', 'gateio'), ('gemini', 'gemini'), ('hitbtc', 'hitbtc'), ('hitbtc3', 'hitbtc3'), ('hollaex', 'hollaex'), ('huobi', 'huobi'), ('huobijp', 'huobijp'), ('huobipro', 'huobipro'), ('idex', 'idex'), ('independentreserve', 'independentreserve'), ('indodax', 'indodax'), ('kraken', 'kraken'), ('krakenfutures', 'krakenfutures'), ('kucoin', 'kucoin'), ('kucoinfutures', 'kucoinfutures'), ('kuna', 'kuna'), ('latoken', 'latoken'), ('lbank', 'lbank'), ('lbank2', 'lbank2'), ('luno', 'luno'), ('lykke', 'lykke'), ('mercado', 'mercado'), ('mexc', 'mexc'), ('mexc3', 'mexc3'), ('ndax', 'ndax'), ('novadax', 'novadax'), ('oceanex', 'oceanex'), ('okcoin', 'okcoin'), ('okex', 'okex'), ('okex5', 'okex5'), ('okx', 'okx'), ('paymium', 'paymium'), ('phemex', 'phemex'), ('poloniex', 'poloniex'), ('poloniexfutures', 'poloniexfutures'), ('probit', 'probit'), ('tidex', 'tidex'), ('timex', 'timex'), ('tokocrypto', 'tokocrypto'), ('upbit', 'upbit'), ('wavesexchange', 'wavesexchange'), ('wazirx', 'wazirx'), ('whitebit', 'whitebit'), ('woo', 'woo'), ('yobit', 'yobit'), ('zaif', 'zaif'), ('zonda', 'zonda')], verbose_name='exhcange')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('apikey', models.CharField(max_length=250, verbose_name='apikey')),
                ('secret_key', models.CharField(max_length=250, verbose_name='secret key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Api container',
                'verbose_name_plural': 'Api containers',
            },
        ),
    ]
