# Generated by Django 4.2.2 on 2023-07-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_apicontainer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicontainer',
            name='secret_key',
            field=models.BinaryField(editable=True, verbose_name='secret key'),
        ),
    ]
