# Generated by Django 4.2.2 on 2023-07-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_apicontainer_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicontainer',
            name='secret_key',
            field=models.BinaryField(blank=True, null=True, verbose_name='secret key'),
        ),
    ]
