# Generated by Django 4.2.2 on 2023-07-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_apicontainer_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.CharField(max_length=50, verbose_name='exchange')),
            ],
            options={
                'verbose_name': 'Exchange model',
                'verbose_name_plural': 'Exchange models',
            },
        ),
    ]
