# Generated by Django 4.2.2 on 2023-07-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_exchangemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangemodel',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50, verbose_name='exchange')),
        ),
    ]
