# Generated by Django 4.2.2 on 2023-07-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_exchangemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemodel',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
